//! Emits `wire_table.rs`: the (id, tag) lookup table the server uses to
//! pair incoming wire frames with their request, response, or
//! subscription role.
//!
//! Per-method `#[wire(...)]` annotations decide id assignment:
//! - request methods reserve `(request_id, response_id)`.
//! - subscription methods reserve `(start_id, stop_id, interrupt_id, receive_id)`.
//!
//! Missing annotations and collisions both hard-fail codegen.

use std::fmt::Write;

use anyhow::Result;
use indoc::{formatdoc, writedoc};

use crate::protocol::ApiDefinition;

use super::const_name;

use crate::protocol::ExpandedWireIds as MethodEntry;

/// Emit a wire table from the validated protocol.
pub fn generate_wire_table(api: &ApiDefinition, schema_hash: &str) -> Result<String> {
    let mut entries: Vec<_> = api
        .traits
        .iter()
        .flat_map(|t| t.methods.iter().map(|m| (m.wire_name.clone(), m.wire_ids)))
        .collect();
    entries.sort_by_key(|(_, ids)| ids.sort_id());
    render(&entries, schema_hash)
}

fn render(methods: &[(String, MethodEntry)], schema_hash: &str) -> Result<String> {
    let mut out = String::new();
    writedoc!(
        out,
        r#"
        //! Wire-protocol discriminant table.
        //!
        //! Auto-generated by truapi-codegen. Do not edit.
        //!
        //! Each method reserves either two ids (request/response) or four
        //! (start/stop/interrupt/receive). The ids for each method are exposed
        //! as a named const (`PREIMAGE_SUBMIT`, ...); [`WIRE_TABLE`] and the
        //! generated dispatcher both reference those consts so the numbers live
        //! in exactly one place. The table is sorted by request/start id.

        /// Request method wire discriminants.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub struct RequestFrameIds {{
            /// Discriminant for the request frame.
            pub request_id: u8,
            /// Discriminant for the response frame.
            pub response_id: u8,
        }}

        /// Subscription method wire discriminants.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub struct SubscriptionFrameIds {{
            /// Discriminant for the start frame.
            pub start_id: u8,
            /// Discriminant for the stop frame.
            pub stop_id: u8,
            /// Discriminant for the interrupt frame (server-initiated termination).
            pub interrupt_id: u8,
            /// Discriminant for each receive frame (a streamed item).
            pub receive_id: u8,
        }}

        /// A single wire-table row.
        pub struct WireEntry {{
            /// Method name from the Rust trait.
            pub method: &'static str,
            /// What kind of slot this entry describes.
            pub kind: WireKind,
        }}

        /// Wire-slot shape: request/response pair or subscription quartet.
        pub enum WireKind {{
            /// Request/response method.
            Request(RequestFrameIds),
            /// Subscription method.
            Subscription(SubscriptionFrameIds),
        }}
        "#
    )
    .unwrap();

    writedoc!(
        out,
        r#"
        /// Fingerprint of this build's wire contract: frame ids, method legs,
        /// sensitivity, and codec version, identical to the TS client's
        /// `TRUAPI_WIRE_SCHEMA_HASH`. A host stamps it on each debug envelope so
        /// the debugger refuses to decode a frame whose contract differs from
        /// its own, even when the coarse handshake codec version is unchanged.
        pub const TRUAPI_WIRE_SCHEMA_HASH: &str = "{schema_hash}";
        "#
    )
    .unwrap();

    // Per-method consts: the single source of truth for each method's ids.
    for (name, entry) in methods {
        let konst = const_name(name);
        let block = match entry {
            MethodEntry::Request {
                request_id,
                response_id,
            } => formatdoc! {
                r#"
                /// Wire discriminants for `{name}`.
                pub const {konst}: RequestFrameIds = RequestFrameIds {{
                    request_id: {request_id},
                    response_id: {response_id},
                }};
                "#
            },
            MethodEntry::Subscription {
                start_id,
                stop_id,
                interrupt_id,
                receive_id,
            } => formatdoc! {
                r#"
                /// Wire discriminants for `{name}`.
                pub const {konst}: SubscriptionFrameIds = SubscriptionFrameIds {{
                    start_id: {start_id},
                    stop_id: {stop_id},
                    interrupt_id: {interrupt_id},
                    receive_id: {receive_id},
                }};
                "#
            },
        };
        out.push('\n');
        out.push_str(&block);
    }

    out.push('\n');
    writedoc!(
        out,
        r#"
        /// The full wire table. Ordering is part of the wire protocol;
        /// only ever append. Removed methods leave their slot empty.
        pub const WIRE_TABLE: &[WireEntry] = &[
        "#
    )
    .unwrap();
    for (name, entry) in methods {
        let konst = const_name(name);
        let variant = match entry {
            MethodEntry::Request { .. } => "Request",
            MethodEntry::Subscription { .. } => "Subscription",
        };
        let block = formatdoc! {
            r#"
            WireEntry {{
                method: "{name}",
                kind: WireKind::{variant}({konst}),
            }},
            "#
        };
        for line in block.lines() {
            writeln!(out, "    {line}").unwrap();
        }
    }
    writeln!(out, "];").unwrap();

    Ok(out)
}
